# Generated by Django 3.1 on 2020-10-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation_code',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
    ]
