# Generated by Django 3.1 on 2020-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0004_confirmation_code_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation_code',
            name='ref',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='confirmation_code',
            name='num',
            field=models.PositiveIntegerField(),
        ),
    ]
