# Generated by Django 3.1 on 2020-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0005_auto_20201103_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation_code',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
