# Generated by Django 3.1 on 2020-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0006_confirmation_code_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='essai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
