# Generated by Django 3.1 on 2020-11-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='essai',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
