# Generated by Django 3.1 on 2020-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0009_auto_20201105_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation_code',
            name='access_success_page',
            field=models.BooleanField(default=False),
        ),
    ]
