# Generated by Django 3.1 on 2020-11-05 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authh', '0010_confirmation_code_access_success_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='has_perm_success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='access_success',
        ),
        migrations.RemoveField(
            model_name='confirmation_code',
            name='access_success_page',
        ),
    ]
