# Generated by Django 3.1 on 2020-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authh', '0011_auto_20201105_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='has_perm_success',
            name='ref',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
