# Generated by Django 3.1 on 2020-12-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0003_auto_20201212_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choosen',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='choice.dish'),
        ),
    ]
