# Generated by Django 3.1 on 2020-12-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0004_user_choosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choosen',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='choice.dish'),
        ),
    ]
