# Generated by Django 3.1 on 2020-12-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0006_remove_user_choosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choosen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='choice.dish'),
        ),
    ]
