# Generated by Django 3.1 on 2020-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0007_user_choosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choosen',
            field=models.PositiveIntegerField(),
        ),
    ]
