# Generated by Django 3.1 on 2020-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0008_auto_20201212_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choosen',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
