# Generated by Django 3.1 on 2020-12-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0009_auto_20201212_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choosen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
