# Generated by Django 3.1 on 2020-12-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0013_auto_20201212_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='choosen',
        ),
    ]
