# Generated by Django 3.1 on 2020-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0014_remove_user_choosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choosen',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
